import Head from "next/head";
import Link from "next/link";
import { Container } from "react-bootstrap";
import ArticleCard from "../components/ArticleCard";
import Landing from "../components/Landing";
import style from "../styles/Index.module.css";

export default function Home({ latest_articles }) {
    return (
        <div>
            <Head>
                <title>academy</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Landing />

            <div className={style.article}>
                <div className={style.articlecontain}>
                    <div className={style.heading}>
                    <h6>Latest articles</h6>
                    <a href="/search">View all</a>
                    </div>
                    
                    {/*make article card*/}
                    <div className={style.articlebox}>
                        {latest_articles.map((article) => {
                            return (
                                <ArticleCard
                                    article={article}
                                    key={article.title}
                                />
                            );
                        })}
                    </div>
                </div>
            </div>
        </div>
    );
}

export const getServerSideProps = async (context) => {
    context.res.setHeader(
        "Cache-Control",
        "public, s-maxage=30, stale-while-revalidate=15"
    );

    const response = await fetch(`${process.env.BASE_URL}/api/articles/latest`);
    const latest_articles = await response.json();

    return { props: { latest_articles } };
};
